# Generated by Django 3.1.4 on 2021-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test',
            field=models.JSONField(null=True),
        ),
    ]
