# Generated by Django 3.1.4 on 2021-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210112_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='test',
            new_name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='area',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_scale',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
