# Generated by Django 3.1.4 on 2021-01-20 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
