# Generated by Django 3.1.7 on 2021-02-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_job_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='region',
        ),
    ]
