# Generated by Django 3.1.7 on 2021-02-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_country'),
        ('portal', '0010_blog_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
