# Generated by Django 3.1.7 on 2021-02-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210225_2252'),
        ('portal', '0012_auto_20210225_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
