# Generated by Django 3.1.7 on 2021-02-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210225_2302'),
        ('portal', '0013_auto_20210225_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
