# Generated by Django 3.1.7 on 2021-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210225_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('france', 'France'), ('germany', 'Germany'), ('malaysia', 'Malaysia'), ('us', 'Us')], max_length=20, null=True)),
            ],
        ),
    ]
