# Generated by Django 3.1.7 on 2021-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('france', 'France'), ('germany', 'Germany'), ('malaysia', 'Malaysia'), ('italy', 'Italy'), ('arabia', 'Arabia'), ('us', 'Us')], max_length=20, null=True),
        ),
    ]
