# Generated by Django 3.1.7 on 2021-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210225_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
