# Generated by Django 3.1.7 on 2021-02-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210225_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='national_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='immigrant',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
