# Generated by Django 3.1.4 on 2020-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20201222_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_date',
        ),
    ]
