# Generated by Django 3.1.4 on 2020-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_remove_notice_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='meeting_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='meeting_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
