# Generated by Django 3.1.4 on 2020-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_auto_20201223_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='meeting_status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
