# Generated by Django 3.1.7 on 2021-02-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0008_auto_20210107_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='region',
            field=models.CharField(choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('France', 'france'), ('Germany', 'Germany'), ('Malaysia', 'Malaysia')], default='Australia', max_length=20, null=True),
        ),
    ]
