# Generated by Django 3.1.7 on 2021-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0009_notice_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='region',
            field=models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('france', 'France'), ('germany', 'Germany'), ('malaysia', 'Malaysia')], default='Australia', max_length=20, null=True),
        ),
    ]
