# Generated by Django 3.1.7 on 2021-02-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0011_auto_20210225_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='region',
        ),
    ]
