# Generated by Django 3.1.7 on 2021-02-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0013_notice_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='region',
        ),
    ]
