# Generated by Django 3.1.7 on 2021-02-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210225_2302'),
        ('desk', '0014_remove_notice_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
